name: Run the simple Node.js app in GitHub actions pipeline and deploying it using the AWS Elastic Beanstalk
on:
  push:
    branches: [main]
jobs:
  first-job:
    runs-on: ubuntu-latest
    container: node
    steps:
      - name: check the node version
        run: node --version
      - name: check the npm version
        run: npm version
      - name: checkout the code from the repos
        uses: actions/checkout@v4
      - name: install the dependencies
        run: npm install
      - name: Update package list
        run: apt-get update -y && apt-get upgrade -y
      - name: install the zip utility
        run: apt-get install zip -y
      - name: genrate the deployemnet package
        run: zip -r nodejs-app-build.zip .
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          application_name: "nodeJS_firstApp_deploy"
          environment_name: "NodeJSfirstAppdeploy-env"
          version_label: "v1.0.0-${{ github.sha }} "
          region: ap-south-1
          deployment_package: nodejs-app-build.zip
